package sudoku.solver;

public class SudokoBoardUI extends javax.swing.JFrame {
    
    /** Creates new form Sudoku Swinger - Puzzle Solver */
    public SudokoBoardUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseButton = new javax.swing.JButton();
        BoxA1 = new javax.swing.JComboBox();
        BoxB1 = new javax.swing.JComboBox();
        BoxC1 = new javax.swing.JComboBox();
        BoxD1 = new javax.swing.JComboBox();
        BoxE1 = new javax.swing.JComboBox();
        BoxF1 = new javax.swing.JComboBox();
        BoxG1 = new javax.swing.JComboBox();
        BoxH1 = new javax.swing.JComboBox();
        BoxI1 = new javax.swing.JComboBox();
        BoxA2 = new javax.swing.JComboBox();
        BoxB2 = new javax.swing.JComboBox();
        BoxC2 = new javax.swing.JComboBox();
        BoxD2 = new javax.swing.JComboBox();
        BoxE2 = new javax.swing.JComboBox();
        BoxF2 = new javax.swing.JComboBox();
        BoxG2 = new javax.swing.JComboBox();
        BoxH2 = new javax.swing.JComboBox();
        BoxI2 = new javax.swing.JComboBox();
        BoxA3 = new javax.swing.JComboBox();
        BoxB3 = new javax.swing.JComboBox();
        BoxC3 = new javax.swing.JComboBox();
        BoxD3 = new javax.swing.JComboBox();
        BoxE3 = new javax.swing.JComboBox();
        BoxF3 = new javax.swing.JComboBox();
        BoxG3 = new javax.swing.JComboBox();
        BoxH3 = new javax.swing.JComboBox();
        BoxI3 = new javax.swing.JComboBox();
        BoxA4 = new javax.swing.JComboBox();
        BoxA5 = new javax.swing.JComboBox();
        BoxA6 = new javax.swing.JComboBox();
        BoxD6 = new javax.swing.JComboBox();
        BoxD5 = new javax.swing.JComboBox();
        BoxD4 = new javax.swing.JComboBox();
        BoxE4 = new javax.swing.JComboBox();
        BoxE5 = new javax.swing.JComboBox();
        BoxE6 = new javax.swing.JComboBox();
        BoxF6 = new javax.swing.JComboBox();
        BoxF5 = new javax.swing.JComboBox();
        BoxF4 = new javax.swing.JComboBox();
        BoxG4 = new javax.swing.JComboBox();
        BoxG5 = new javax.swing.JComboBox();
        BoxG6 = new javax.swing.JComboBox();
        BoxH6 = new javax.swing.JComboBox();
        BoxH5 = new javax.swing.JComboBox();
        BoxH4 = new javax.swing.JComboBox();
        BoxI4 = new javax.swing.JComboBox();
        BoxI5 = new javax.swing.JComboBox();
        BoxI6 = new javax.swing.JComboBox();
        BoxB4 = new javax.swing.JComboBox();
        BoxB5 = new javax.swing.JComboBox();
        BoxB6 = new javax.swing.JComboBox();
        BoxC6 = new javax.swing.JComboBox();
        BoxC5 = new javax.swing.JComboBox();
        BoxC4 = new javax.swing.JComboBox();
        BoxI7 = new javax.swing.JComboBox();
        BoxI8 = new javax.swing.JComboBox();
        BoxI9 = new javax.swing.JComboBox();
        BoxH9 = new javax.swing.JComboBox();
        BoxH8 = new javax.swing.JComboBox();
        BoxH7 = new javax.swing.JComboBox();
        BoxG7 = new javax.swing.JComboBox();
        BoxG8 = new javax.swing.JComboBox();
        BoxG9 = new javax.swing.JComboBox();
        BoxF7 = new javax.swing.JComboBox();
        BoxF8 = new javax.swing.JComboBox();
        BoxF9 = new javax.swing.JComboBox();
        BoxE9 = new javax.swing.JComboBox();
        BoxE8 = new javax.swing.JComboBox();
        BoxE7 = new javax.swing.JComboBox();
        BoxD7 = new javax.swing.JComboBox();
        BoxD8 = new javax.swing.JComboBox();
        BoxD9 = new javax.swing.JComboBox();
        BoxA7 = new javax.swing.JComboBox();
        BoxA8 = new javax.swing.JComboBox();
        BoxA9 = new javax.swing.JComboBox();
        BoxB7 = new javax.swing.JComboBox();
        BoxB8 = new javax.swing.JComboBox();
        BoxB9 = new javax.swing.JComboBox();
        BoxC7 = new javax.swing.JComboBox();
        BoxC8 = new javax.swing.JComboBox();
        BoxC9 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        SudokuSolverLabel = new javax.swing.JLabel();
        PuzzleSolverLabel = new javax.swing.JLabel();
        ALabel = new javax.swing.JLabel();
        BLabel = new javax.swing.JLabel();
        CLabel = new javax.swing.JLabel();
        DLabel = new javax.swing.JLabel();
        ELabel = new javax.swing.JLabel();
        FLabel = new javax.swing.JLabel();
        GLabel = new javax.swing.JLabel();
        HLabel = new javax.swing.JLabel();
        ILabel = new javax.swing.JLabel();
        SolveButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Swinger - Puzzle Solver");

        CloseButton.setText("Close");

        BoxA1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA1ActionPerformed(evt);
            }
        });

        BoxB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB1ActionPerformed(evt);
            }
        });

        BoxC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC1ActionPerformed(evt);
            }
        });

        BoxD1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD1ActionPerformed(evt);
            }
        });

        BoxE1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE1ActionPerformed(evt);
            }
        });

        BoxF1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF1ActionPerformed(evt);
            }
        });

        BoxG1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG1ActionPerformed(evt);
            }
        });

        BoxH1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH1ActionPerformed(evt);
            }
        });

        BoxI1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI1ActionPerformed(evt);
            }
        });

        BoxA2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA2ActionPerformed(evt);
            }
        });

        BoxB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB2ActionPerformed(evt);
            }
        });

        BoxC2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC2ActionPerformed(evt);
            }
        });

        BoxD2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD2ActionPerformed(evt);
            }
        });

        BoxE2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE2ActionPerformed(evt);
            }
        });

        BoxF2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF2ActionPerformed(evt);
            }
        });

        BoxG2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG2ActionPerformed(evt);
            }
        });

        BoxH2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH2ActionPerformed(evt);
            }
        });

        BoxI2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI2ActionPerformed(evt);
            }
        });

        BoxA3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA3ActionPerformed(evt);
            }
        });

        BoxB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB3ActionPerformed(evt);
            }
        });

        BoxC3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC3ActionPerformed(evt);
            }
        });

        BoxD3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD3ActionPerformed(evt);
            }
        });

        BoxE3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE3ActionPerformed(evt);
            }
        });

        BoxF3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF3ActionPerformed(evt);
            }
        });

        BoxG3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG3ActionPerformed(evt);
            }
        });

        BoxH3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH3ActionPerformed(evt);
            }
        });

        BoxI3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI3ActionPerformed(evt);
            }
        });

        BoxA4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA4ActionPerformed(evt);
            }
        });

        BoxA5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA5ActionPerformed(evt);
            }
        });

        BoxA6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA6ActionPerformed(evt);
            }
        });

        BoxD6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD6ActionPerformed(evt);
            }
        });

        BoxD5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD5ActionPerformed(evt);
            }
        });

        BoxD4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD4ActionPerformed(evt);
            }
        });

        BoxE4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE4ActionPerformed(evt);
            }
        });

        BoxE5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE5ActionPerformed(evt);
            }
        });

        BoxE6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE6ActionPerformed(evt);
            }
        });

        BoxF6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF6ActionPerformed(evt);
            }
        });

        BoxF5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF5ActionPerformed(evt);
            }
        });

        BoxF4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF4ActionPerformed(evt);
            }
        });

        BoxG4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG4ActionPerformed(evt);
            }
        });

        BoxG5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG5ActionPerformed(evt);
            }
        });

        BoxG6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG6ActionPerformed(evt);
            }
        });

        BoxH6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH6ActionPerformed(evt);
            }
        });

        BoxH5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH5ActionPerformed(evt);
            }
        });

        BoxH4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH4ActionPerformed(evt);
            }
        });

        BoxI4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI4ActionPerformed(evt);
            }
        });

        BoxI5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI5ActionPerformed(evt);
            }
        });

        BoxI6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI6ActionPerformed(evt);
            }
        });

        BoxB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB4ActionPerformed(evt);
            }
        });

        BoxB5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB5ActionPerformed(evt);
            }
        });

        BoxB6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB6ActionPerformed(evt);
            }
        });

        BoxC6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC6ActionPerformed(evt);
            }
        });

        BoxC5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC5ActionPerformed(evt);
            }
        });

        BoxC4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC4ActionPerformed(evt);
            }
        });

        BoxI7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI7ActionPerformed(evt);
            }
        });

        BoxI8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI8ActionPerformed(evt);
            }
        });

        BoxI9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxI9ActionPerformed(evt);
            }
        });

        BoxH9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH9ActionPerformed(evt);
            }
        });

        BoxH8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH8ActionPerformed(evt);
            }
        });

        BoxH7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxH7ActionPerformed(evt);
            }
        });

        BoxG7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG7ActionPerformed(evt);
            }
        });

        BoxG8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG8ActionPerformed(evt);
            }
        });

        BoxG9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxG9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxG9ActionPerformed(evt);
            }
        });

        BoxF7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF7ActionPerformed(evt);
            }
        });

        BoxF8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF8ActionPerformed(evt);
            }
        });

        BoxF9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxF9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxF9ActionPerformed(evt);
            }
        });

        BoxE9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE9ActionPerformed(evt);
            }
        });

        BoxE8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE8ActionPerformed(evt);
            }
        });

        BoxE7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxE7ActionPerformed(evt);
            }
        });

        BoxD7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD7ActionPerformed(evt);
            }
        });

        BoxD8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD8ActionPerformed(evt);
            }
        });

        BoxD9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxD9ActionPerformed(evt);
            }
        });

        BoxA7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA7ActionPerformed(evt);
            }
        });

        BoxA8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA8ActionPerformed(evt);
            }
        });

        BoxA9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxA9ActionPerformed(evt);
            }
        });

        BoxB7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB7ActionPerformed(evt);
            }
        });

        BoxB8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB8ActionPerformed(evt);
            }
        });

        BoxB9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxB9ActionPerformed(evt);
            }
        });

        BoxC7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC7ActionPerformed(evt);
            }
        });

        BoxC8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC8ActionPerformed(evt);
            }
        });

        BoxC9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        BoxC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxC9ActionPerformed(evt);
            }
        });

        jLabel1.setText("     1               2               3                      4                5               6                      7                8               9");

        SudokuSolverLabel.setText("SUDOKU SWINGER");

        PuzzleSolverLabel.setText("Puzzle Solver");

        ALabel.setText("A");

        BLabel.setText("B");

        CLabel.setText("C");

        DLabel.setText("D");

        ELabel.setText("E");

        FLabel.setText("F");

        GLabel.setText("G");

        HLabel.setText("H");

        ILabel.setText("I");

        SolveButton.setText("SOLVE");
        SolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("CLEAR");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ALabel)
                    .add(BLabel)
                    .add(CLabel)
                    .add(DLabel)
                    .add(ELabel)
                    .add(FLabel)
                    .add(GLabel)
                    .add(HLabel)
                    .add(ILabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(52, 52, 52)
                        .add(SudokuSolverLabel))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(BoxA1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxB1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxC1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxD1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxE1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxG1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxH1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxI1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxA2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxB2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxC2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxD2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxE2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxF2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxA3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxB3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxC3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxD3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxE3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxF3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxG2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxH2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxI2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxG3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxH3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxI3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(BoxA4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxD4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxE4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxF4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxG4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxH4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxI4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxB4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxC4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxA5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxD5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxE5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxF5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxB5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxC5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxA6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxD6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxE6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxF6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxB6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxC6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxG5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxH5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxI5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxG6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxH6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxI6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(BoxI7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxH7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxG7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxF7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxE7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxD7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxA7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxB7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BoxC7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxF8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxE8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxD8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxA8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxB8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxC8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxB9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxA9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxC9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxD9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxE9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxF9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(34, 34, 34)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(PuzzleSolverLabel)
                                    .add(ClearButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(SolveButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BoxI8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxH8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxG8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(BoxI9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(CloseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(BoxH9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BoxG9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(PuzzleSolverLabel)
                        .add(18, 18, 18)
                        .add(SolveButton)
                        .add(13, 13, 13)
                        .add(ClearButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(CloseButton))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(SudokuSolverLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(38, 38, 38)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxB1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BLabel))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxC1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(CLabel))
                                        .add(26, 26, 26)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxD1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(DLabel))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxE1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(ELabel))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(FLabel)))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxA2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxA1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(ALabel))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxC2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(BoxD2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxE2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxF2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(BoxA3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxC3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(BoxD3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxE3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxF3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(27, 27, 27)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxG2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxG1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(GLabel))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxH2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxH1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(HLabel))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxI2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxI1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(ILabel)))
                                    .add(layout.createSequentialGroup()
                                        .add(BoxG3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxH3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxI3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(BoxA4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxC4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(BoxD4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxE4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxF4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(BoxA5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxC5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(BoxD5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxE5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxF5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(BoxA6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxC6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(BoxD6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxE6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxF6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(27, 27, 27)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxG5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxG4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxH5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxH4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxI5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxI4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(layout.createSequentialGroup()
                                        .add(BoxG6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxH6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxI6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(BoxA7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxC7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(BoxD7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxE7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxF7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxA8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxA9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxB8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxC8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxC9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(26, 26, 26)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxD8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxD9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxE8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxE9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxF8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxF9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(layout.createSequentialGroup()
                                        .add(38, 38, 38)
                                        .add(BoxB9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(27, 27, 27)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxG8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxG7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxH8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxH7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(BoxI8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(BoxI7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(layout.createSequentialGroup()
                                        .add(BoxG9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxH9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(BoxI9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA1ActionPerformed

    private void BoxB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB1ActionPerformed

    private void BoxC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC1ActionPerformed

    private void BoxD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD1ActionPerformed

    private void BoxE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE1ActionPerformed

    private void BoxF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF1ActionPerformed

    private void BoxG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG1ActionPerformed

    private void BoxH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH1ActionPerformed

    private void BoxI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI1ActionPerformed

    private void BoxA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA2ActionPerformed

    private void BoxB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB2ActionPerformed

    private void BoxC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC2ActionPerformed

    private void BoxD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD2ActionPerformed

    private void BoxE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE2ActionPerformed

    private void BoxF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF2ActionPerformed

    private void BoxG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG2ActionPerformed

    private void BoxH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH2ActionPerformed

    private void BoxI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI2ActionPerformed

    private void BoxA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA3ActionPerformed

    private void BoxB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB3ActionPerformed

    private void BoxC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC3ActionPerformed

    private void BoxD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD3ActionPerformed

    private void BoxE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE3ActionPerformed

    private void BoxF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF3ActionPerformed

    private void BoxG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG3ActionPerformed

    private void BoxH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH3ActionPerformed

    private void BoxI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI3ActionPerformed

    private void BoxA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA4ActionPerformed

    private void BoxA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA5ActionPerformed

    private void BoxA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA6ActionPerformed

    private void BoxD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD6ActionPerformed

    private void BoxD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD5ActionPerformed

    private void BoxD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD4ActionPerformed

    private void BoxE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE4ActionPerformed

    private void BoxE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE5ActionPerformed

    private void BoxE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE6ActionPerformed

    private void BoxF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF6ActionPerformed

    private void BoxF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF5ActionPerformed

    private void BoxF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF4ActionPerformed

    private void BoxG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG4ActionPerformed

    private void BoxG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG5ActionPerformed

    private void BoxG6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG6ActionPerformed

    private void BoxH6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH6ActionPerformed

    private void BoxH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH5ActionPerformed

    private void BoxH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH4ActionPerformed

    private void BoxI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI4ActionPerformed

    private void BoxI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI5ActionPerformed

    private void BoxI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI6ActionPerformed

    private void BoxB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB4ActionPerformed

    private void BoxB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB5ActionPerformed

    private void BoxB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB6ActionPerformed

    private void BoxC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC6ActionPerformed

    private void BoxC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC5ActionPerformed

    private void BoxC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC4ActionPerformed

    private void BoxI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI7ActionPerformed

    private void BoxI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI8ActionPerformed

    private void BoxI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxI9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxI9ActionPerformed

    private void BoxH9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH9ActionPerformed

    private void BoxH8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH8ActionPerformed

    private void BoxH7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxH7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxH7ActionPerformed

    private void BoxG7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG7ActionPerformed

    private void BoxG8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG8ActionPerformed

    private void BoxG9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxG9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxG9ActionPerformed

    private void BoxF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF7ActionPerformed

    private void BoxF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF8ActionPerformed

    private void BoxF9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxF9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxF9ActionPerformed

    private void BoxE9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE9ActionPerformed

    private void BoxE8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE8ActionPerformed

    private void BoxE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxE7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxE7ActionPerformed

    private void BoxD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD7ActionPerformed

    private void BoxD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD8ActionPerformed

    private void BoxD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxD9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxD9ActionPerformed

    private void BoxA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA7ActionPerformed

    private void BoxA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA8ActionPerformed

    private void BoxA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxA9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxA9ActionPerformed

    private void BoxB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB7ActionPerformed

    private void BoxB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB8ActionPerformed

    private void BoxB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxB9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxB9ActionPerformed

    private void BoxC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC7ActionPerformed

    private void BoxC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC8ActionPerformed

    private void BoxC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxC9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxC9ActionPerformed

    private void SolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolveButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokoBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokoBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokoBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokoBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokoBoardUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JLabel BLabel;
    private javax.swing.JComboBox BoxA1;
    private javax.swing.JComboBox BoxA2;
    private javax.swing.JComboBox BoxA3;
    private javax.swing.JComboBox BoxA4;
    private javax.swing.JComboBox BoxA5;
    private javax.swing.JComboBox BoxA6;
    private javax.swing.JComboBox BoxA7;
    private javax.swing.JComboBox BoxA8;
    private javax.swing.JComboBox BoxA9;
    private javax.swing.JComboBox BoxB1;
    private javax.swing.JComboBox BoxB2;
    private javax.swing.JComboBox BoxB3;
    private javax.swing.JComboBox BoxB4;
    private javax.swing.JComboBox BoxB5;
    private javax.swing.JComboBox BoxB6;
    private javax.swing.JComboBox BoxB7;
    private javax.swing.JComboBox BoxB8;
    private javax.swing.JComboBox BoxB9;
    private javax.swing.JComboBox BoxC1;
    private javax.swing.JComboBox BoxC2;
    private javax.swing.JComboBox BoxC3;
    private javax.swing.JComboBox BoxC4;
    private javax.swing.JComboBox BoxC5;
    private javax.swing.JComboBox BoxC6;
    private javax.swing.JComboBox BoxC7;
    private javax.swing.JComboBox BoxC8;
    private javax.swing.JComboBox BoxC9;
    private javax.swing.JComboBox BoxD1;
    private javax.swing.JComboBox BoxD2;
    private javax.swing.JComboBox BoxD3;
    private javax.swing.JComboBox BoxD4;
    private javax.swing.JComboBox BoxD5;
    private javax.swing.JComboBox BoxD6;
    private javax.swing.JComboBox BoxD7;
    private javax.swing.JComboBox BoxD8;
    private javax.swing.JComboBox BoxD9;
    private javax.swing.JComboBox BoxE1;
    private javax.swing.JComboBox BoxE2;
    private javax.swing.JComboBox BoxE3;
    private javax.swing.JComboBox BoxE4;
    private javax.swing.JComboBox BoxE5;
    private javax.swing.JComboBox BoxE6;
    private javax.swing.JComboBox BoxE7;
    private javax.swing.JComboBox BoxE8;
    private javax.swing.JComboBox BoxE9;
    private javax.swing.JComboBox BoxF1;
    private javax.swing.JComboBox BoxF2;
    private javax.swing.JComboBox BoxF3;
    private javax.swing.JComboBox BoxF4;
    private javax.swing.JComboBox BoxF5;
    private javax.swing.JComboBox BoxF6;
    private javax.swing.JComboBox BoxF7;
    private javax.swing.JComboBox BoxF8;
    private javax.swing.JComboBox BoxF9;
    private javax.swing.JComboBox BoxG1;
    private javax.swing.JComboBox BoxG2;
    private javax.swing.JComboBox BoxG3;
    private javax.swing.JComboBox BoxG4;
    private javax.swing.JComboBox BoxG5;
    private javax.swing.JComboBox BoxG6;
    private javax.swing.JComboBox BoxG7;
    private javax.swing.JComboBox BoxG8;
    private javax.swing.JComboBox BoxG9;
    private javax.swing.JComboBox BoxH1;
    private javax.swing.JComboBox BoxH2;
    private javax.swing.JComboBox BoxH3;
    private javax.swing.JComboBox BoxH4;
    private javax.swing.JComboBox BoxH5;
    private javax.swing.JComboBox BoxH6;
    private javax.swing.JComboBox BoxH7;
    private javax.swing.JComboBox BoxH8;
    private javax.swing.JComboBox BoxH9;
    private javax.swing.JComboBox BoxI1;
    private javax.swing.JComboBox BoxI2;
    private javax.swing.JComboBox BoxI3;
    private javax.swing.JComboBox BoxI4;
    private javax.swing.JComboBox BoxI5;
    private javax.swing.JComboBox BoxI6;
    private javax.swing.JComboBox BoxI7;
    private javax.swing.JComboBox BoxI8;
    private javax.swing.JComboBox BoxI9;
    private javax.swing.JLabel CLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel DLabel;
    private javax.swing.JLabel ELabel;
    private javax.swing.JLabel FLabel;
    private javax.swing.JLabel GLabel;
    private javax.swing.JLabel HLabel;
    private javax.swing.JLabel ILabel;
    private javax.swing.JLabel PuzzleSolverLabel;
    private javax.swing.JButton SolveButton;
    private javax.swing.JLabel SudokuSolverLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
